#!/usr/bin/env bash
#hola
d="/etc/passwd"
while IFS=: read -r u gID Di CS uID pswd uIDi   
do
	echo"The user $u is part of the $gID gang, lives in $Di and rides $CS. $uID's place is protected by the passcode $pswd, more info about the user here: $iIDi"
done < "$d"
