#!/usr/bin/env bash
#hola
echo $$ > /var/run/myscript.pid
trap 'echo Y U no love me' 2
trap 'echo I hate the kill command' 15
trap 'rm /var/run/myscript.pid || exit' 3 15 
while true
do
	echo "To infinity and beyond"
	sleep 2
done
